require "luis.options"
require "luis.keymaps"
require "luis.plugins"
require "luis.colorscheme"
require "luis.lsp-zero"
require "luis.nvimtree"
-- require "luis.treesitter"
require "luis.autopairs"
require "luis.comment"
require "luis.heirline"
require "luis.bufferline"
require "luis.toggleterm"
require "luis.colorizer"
require "luis.gitsigns"
